version: 0.0
os: linux
files:
 - source: .
   destination: /home/ec2-user/github-actions-demo
hooks:
  BeforeInstall:
  - location: scripts/before_install.sh
    timeout: 300
    runas: ec2-user
  AfterInstall:
   - location: scripts/install_app_dependencies.sh
     timeout: 300
     runas: ec2-user
  ApplicationStart:
   - location: scripts/start_server.sh
     timeout: 300
     runas: ec2-user
